/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author RPL 2
 */
public class FormGuru extends javax.swing.JFrame {
  private DefaultTableModel tabmode;
  private ResultSet hasil;
  CrudGuru crud = new CrudGuru();
  /**
   * Creates new form FormGuru
   */
  public FormGuru() throws SQLException{
    initComponents();
    tampil_database();
  }

  public void tampil_database(){
    Object[] baris = {"NIP","Nama","Tgl Lahir","Alamat","Mapel"};
    tabmode = new DefaultTableModel(null,baris);
    tabel_guru.setModel(tabmode);
    try{
      hasil = crud.tampil_data();
      while(hasil.next()){
        crud.setNip(hasil.getString("nip"));
        crud.setNama(hasil.getString("nama"));
        crud.setTglLahir(hasil.getString("tgl_lahir"));
        crud.setAlamat(hasil.getString("alamat"));
        crud.setMapel(hasil.getString("mapel"));
        String[] data = {crud.getNip(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMapel()};
        tabmode.addRow(data);
      }
    } catch(Exception e){}
  }

  public void reset_text(){
    txt_nip.setText("");
    txt_nama.setText("");
    txt_tgl_lahir.setText("");
    txt_alamat.setText("");
    txt_mapel.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tgl_lahir = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nip = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_mapel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_guru = new javax.swing.JTable();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_semua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Guru");

        jLabel2.setText("NIP");

        jLabel3.setText("Nama");

        jLabel4.setText("Tgl Lahir");

        jLabel5.setText("Alamat");

        jLabel6.setText("Mapel");

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        tabel_guru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIP", "Nama", "Tgl Lahir", "Alamat", "Mapel"
            }
        ));
        tabel_guru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_guruMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_guru);

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        jLabel7.setText("Cari Data (NIP)");

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_semua.setText("Semua Data");
        btn_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_semuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_nip)
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn_simpan)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_reset)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_ubah)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_hapus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btn_keluar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btn_cari)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(btn_semua))
                                        .addComponent(txt_cari))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_alamat)
                            .addComponent(txt_mapel))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(368, 368, 368)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tgl_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_mapel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_reset)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_keluar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_cari)
                            .addComponent(btn_semua)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    if(txt_nip.getText().trim().equals("")){
      JOptionPane.showMessageDialog(null, "NIP belum diisi!");
      txt_nip.requestFocus();
    }else if(txt_nama.getText().trim().equals("")){
      JOptionPane.showMessageDialog(null, "Nama belum diisi!");
      txt_nama.requestFocus();
    }else if(txt_tgl_lahir.getText().trim().equals("")){
      JOptionPane.showMessageDialog(null, "Tanggal lahir belum diisi!");
      txt_tgl_lahir.requestFocus();
    }else if(txt_alamat.getText().trim().equals("")){
      JOptionPane.showMessageDialog(null, "Alamat lahir belum diisi!");
      txt_alamat.requestFocus();
    }else if(txt_mapel.getText().trim().equals("")){
      JOptionPane.showMessageDialog(null, "Mapel belum diisi!");
      txt_mapel.requestFocus();
    }else{
      try{
        crud.setNip(txt_nip.getText());
        crud.setNama(txt_nama.getText());
        crud.setTglLahir(txt_tgl_lahir.getText());
        crud.setAlamat(txt_alamat.getText());
        crud.setMapel(txt_mapel.getText());
        crud.tambah_data(crud.getNip(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMapel());
        tampil_database();
        reset_text();
      }catch(Exception e){}
    }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
      reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
      if(txt_nip.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "NIP belum diisi!");
        txt_nip.requestFocus();
      }else if(txt_nama.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nama belum diisi!");
        txt_nama.requestFocus();
      }else if(txt_tgl_lahir.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Tanggal lahir belum diisi!");
        txt_tgl_lahir.requestFocus();
      }else if(txt_alamat.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Alamat lahir belum diisi!");
        txt_alamat.requestFocus();
      }else if(txt_mapel.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Mapel belum diisi!");
        txt_mapel.requestFocus();
      }else{
        try{
          crud.setNip(txt_nip.getText());
          crud.setNama(txt_nama.getText());
          crud.setTglLahir(txt_tgl_lahir.getText());
          crud.setAlamat(txt_alamat.getText());
          crud.setMapel(txt_mapel.getText());
          crud.ubah_data(crud.getNip(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMapel());
          tampil_database();
          reset_text();
        }catch(Exception e){
          System.out.println(e);
        }
      }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
      if(txt_nip.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf,NIP belum diisi!");
        txt_nip.requestFocus();
      } else{
        if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin menghapus data?","Warning",2)==JOptionPane.YES_OPTION){
          try{
            crud.setNip(txt_nip.getText());
            crud.hapus_data(crud.getNip());
            tampil_database();
            reset_text();
          }catch(Exception e){}
        }
      }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
      if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?","Warning",2)==JOptionPane.YES_OPTION){
        System.exit(0);
      }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_semuaActionPerformed
      tampil_database();
    }//GEN-LAST:event_btn_semuaActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
      if(txt_cari.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Kolom pencarian belum diisi!");
        txt_cari.requestFocus();
      }else{
        Object[] baris = {"NIP","Nama","Tgl Lahir","Alamat","Mapel"};
        tabmode = new DefaultTableModel(null,baris);
        tabel_guru.setModel(tabmode);
        try{
          hasil = crud.cari_data(txt_cari.getText());
          while(hasil.next()){
            crud.setNip(hasil.getString("nip"));
            crud.setNama(hasil.getString("nama"));
            crud.setTglLahir(hasil.getString("tgl_lahir"));
            crud.setAlamat(hasil.getString("alamat"));
            crud.setMapel(hasil.getString("mapel"));
            String[] data = {crud.getNip(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMapel()};
            tabmode.addRow(data);
           }
        } catch(Exception e){}
      }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void tabel_guruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_guruMouseClicked
      try{
        int row =  tabel_guru.rowAtPoint(evt.getPoint());

        String nip = tabel_guru.getValueAt(row, 0).toString();
        String nama = tabel_guru.getValueAt(row, 1).toString();
        String tgl_lahir = tabel_guru.getValueAt(row, 2).toString();
        String alamat = tabel_guru.getValueAt(row, 3).toString();
        String mapel = tabel_guru.getValueAt(row, 4).toString();
        txt_nip.setText(String.valueOf(nip));
        txt_nama.setText(String.valueOf(nama));
        txt_tgl_lahir.setText(String.valueOf(tgl_lahir));
        txt_alamat.setText(String.valueOf(alamat));
        txt_mapel.setText(String.valueOf(mapel));
      }catch(Exception e){}
    }//GEN-LAST:event_tabel_guruMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGuru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FormGuru().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormGuru.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_semua;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_guru;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_mapel;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nip;
    private javax.swing.JTextField txt_tgl_lahir;
    // End of variables declaration//GEN-END:variables
}
