/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author RPL 2
 */
public class FormSiswa extends javax.swing.JFrame {
  private ResultSet hasil;
  private DefaultTableModel tabmode;

  Crud crud = new Crud();


  /**
   * Creates new form FormSiswa
   */
  public FormSiswa() throws SQLException{
    initComponents();
    tampil_database();
  }

  public void tampil_database(){
    Object[] baris = {"NIS","Nama","Tgl Lahir","Alamat","Nilai MM","Nilai IPA","Nilai BI","Nilai BING"};
    tabmode = new DefaultTableModel(null,baris);
    tabel_siswa.setModel(tabmode);
    try{
      hasil = crud.tampil_data();
      while(hasil.next()){
        crud.setNis(hasil.getString("nis"));
        crud.setNama(hasil.getString("nama"));
        crud.setTglLahir(hasil.getString("tgl_lahir"));
        crud.setAlamat(hasil.getString("alamat"));
        crud.setMm(hasil.getString("nilai_mm"));
        crud.setIpa(hasil.getString("nilai_ipa"));
        crud.setBi(hasil.getString("nilai_bi"));
        crud.setBing(hasil.getString("nilai_bing"));
        String[] data = {crud.getNis(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMm(),crud.getIpa(),crud.getBi(),crud.getBing()};
        tabmode.addRow(data);
        }
    } catch(Exception e){
    }
  }

  public void reset_text(){
    txt_nis.setText("");
    txt_nama.setText("");
    txt_tgl_lahir.setText("");
    txt_alamat.setText("");
    txt_mm.setText("");
    txt_ipa.setText("");
    txt_bi.setText("");
    txt_bing.setText("");
  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_bing = new javax.swing.JTextField();
        txt_tgl_lahir = new javax.swing.JTextField();
        txt_bi = new javax.swing.JTextField();
        txt_mm = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_nis = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_siswa = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_cari = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        btn_cari = new javax.swing.JButton();
        btn_semua = new javax.swing.JButton();
        btn_rata_kelas = new javax.swing.JButton();
        btn_peringkat = new javax.swing.JButton();
        btn_rata_mapel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_ipa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data Siswa");

        jLabel2.setText("NIS");

        jLabel3.setText("Nama");

        jLabel4.setText("Tgl lahir");

        jLabel5.setText("Alamat");

        jLabel6.setText("Nilai MM");

        jLabel7.setText("Nilai IPA");

        jLabel8.setText("Nilai BI");

        jLabel9.setText("Nilai BING");

        txt_bi.setText(" ");

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });

        tabel_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tgl Lahir", "Alamat", "Nilai MM", "Nilai IPA", "Nilai BI", "Nilai BING"
            }
        ));
        tabel_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_siswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_siswa);

        jLabel10.setText("Cari Data (NIS)");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });

        btn_semua.setText("Semua Data");
        btn_semua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_semuaActionPerformed(evt);
            }
        });

        btn_rata_kelas.setText("Rata-Rata Kelas");
        btn_rata_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rata_kelasActionPerformed(evt);
            }
        });

        btn_peringkat.setText("Peringkat Siswa");
        btn_peringkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_peringkatActionPerformed(evt);
            }
        });

        btn_rata_mapel.setText("Rata-Rata Mapel");
        btn_rata_mapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rata_mapelActionPerformed(evt);
            }
        });

        jLabel11.setText("Pilih Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_nis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_tgl_lahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_bing)
                                    .addComponent(txt_bi, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_mm, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_ipa, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_keluar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_semua))
                            .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_rata_kelas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_rata_mapel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_peringkat))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_nis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_mm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_ipa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_bi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txt_bing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_reset)
                            .addComponent(btn_ubah)
                            .addComponent(btn_hapus)
                            .addComponent(btn_keluar)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cari)
                    .addComponent(btn_semua)
                    .addComponent(btn_rata_kelas)
                    .addComponent(btn_rata_mapel)
                    .addComponent(btn_peringkat))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
      if(txt_nis.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "NIS belum diisi!");
        txt_nis.requestFocus();
      }else if(txt_nama.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nama belum diisi!");
        txt_nama.requestFocus();
      }else if(txt_tgl_lahir.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Tanggal lahir belum diisi!");
        txt_tgl_lahir.requestFocus();
      }else if(txt_alamat.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Alamat lahir belum diisi!");
        txt_alamat.requestFocus();
      }else if(txt_mm.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai MM belum diisi!");
        txt_mm.requestFocus();
      }else if(txt_ipa.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai IPA belum diisi!");
        txt_ipa.requestFocus();
      }else if(txt_bi.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai B.Indonesia belum diisi!");
        txt_bi.requestFocus();
      }else if(txt_bing.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai B.Inggris belum diisi!");
        txt_bing.requestFocus();
      }else{
        try{
          crud.setNis(txt_nis.getText());
          crud.setNama(txt_nama.getText());
          crud.setTglLahir(txt_tgl_lahir.getText());
          crud.setAlamat(txt_alamat.getText());
          crud.setMm(txt_mm.getText());
          crud.setIpa(txt_ipa.getText());
          crud.setBi(txt_bi.getText());
          crud.setBing(txt_bing.getText());
          crud.tambah_data(crud.getNis(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMm(),crud.getIpa(),crud.getBi(),crud.getBing());
          tampil_database();
          reset_text();
        }catch(Exception e){}
      }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
      reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
      if(txt_nis.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "NIS belum diisi!");
        txt_nis.requestFocus();
      }else if(txt_nama.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nama belum diisi!");
        txt_nama.requestFocus();
      }else if(txt_tgl_lahir.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Tanggal lahir belum diisi!");
        txt_tgl_lahir.requestFocus();
      }else if(txt_alamat.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Alamat lahir belum diisi!");
        txt_alamat.requestFocus();
      }else if(txt_mm.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai MM belum diisi!");
        txt_mm.requestFocus();
      }else if(txt_ipa.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai IPA belum diisi!");
        txt_ipa.requestFocus();
      }else if(txt_bi.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai B.Indonesia belum diisi!");
        txt_bi.requestFocus();
      }else if(txt_bing.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null, "Nilai B.Inggris belum diisi!");
        txt_bing.requestFocus();
      }else{
        try{
          crud.setNis(txt_nis.getText());
          crud.setNama(txt_nama.getText());
          crud.setTglLahir(txt_tgl_lahir.getText());
          crud.setAlamat(txt_alamat.getText());
          crud.setMm(txt_mm.getText());
          crud.setIpa(txt_ipa.getText());
          crud.setBi(txt_bi.getText());
          crud.setBing(txt_bing.getText());
          crud.ubah_data(crud.getNis(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMm(),crud.getIpa(),crud.getBi(),crud.getBing());
          tampil_database();
          reset_text();
        }catch(Exception e){}
      }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
      if(txt_nis.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Maaf,NIS belum diisi!");
        txt_nis.requestFocus();
      } else{
        if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin menghapus data?","Warning",2)==JOptionPane.YES_OPTION){
          try{
            crud.setNis(txt_nis.getText());
            crud.hapus_data(crud.getNis());
            tampil_database();
            reset_text();
          }catch(Exception e){}
        }
      }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
      if(JOptionPane.showConfirmDialog(null, "Apakah Anda yakin keluar?","Warning",2)==JOptionPane.YES_OPTION){
        System.exit(0);
      }
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
      if(txt_cari.getText().trim().equals("")){
        JOptionPane.showMessageDialog(null,"Kolom pencarian belum diisi!");
        txt_cari.requestFocus();
      }else{
        Object[] baris = {"NIS","Nama","Tgl Lahir","Alamat","Nilai MM","Nilai IPA","Nilai BI","Nilai BING"};
        tabmode = new DefaultTableModel(null,baris);
        tabel_siswa.setModel(tabmode);
        try{
          hasil = crud.cari_data(txt_cari.getText());
          while(hasil.next()){
            crud.setNis(hasil.getString("nis"));
            crud.setNama(hasil.getString("nama"));
            crud.setTglLahir(hasil.getString("tgl_lahir"));
            crud.setAlamat(hasil.getString("alamat"));
            crud.setMm(hasil.getString("nilai_mm"));
            crud.setIpa(hasil.getString("nilai_ipa"));
            crud.setBi(hasil.getString("nilai_bi"));
            crud.setBing(hasil.getString("nilai_bing"));
            String[] data = {crud.getNis(),crud.getNama(),crud.getTglLahir(),crud.getAlamat(),crud.getMm(),crud.getIpa(),crud.getBi(),crud.getBing()};
            tabmode.addRow(data);
            }
        } catch(Exception e){
        }
      }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_semuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_semuaActionPerformed
        tampil_database();
    }//GEN-LAST:event_btn_semuaActionPerformed

    private void tabel_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_siswaMouseClicked
      try{
        int row =  tabel_siswa.rowAtPoint(evt.getPoint());

        String nis = tabel_siswa.getValueAt(row, 0).toString();
        String nama = tabel_siswa.getValueAt(row, 1).toString();
        String tgl_lahir = tabel_siswa.getValueAt(row, 2).toString();
        String alamat = tabel_siswa.getValueAt(row, 3).toString();
        String nilai_mm = tabel_siswa.getValueAt(row, 4).toString();
        String nilai_ipa = tabel_siswa.getValueAt(row, 5).toString();
        String nilai_bi = tabel_siswa.getValueAt(row, 6).toString();
        String nilai_bing = tabel_siswa.getValueAt(row, 7).toString();
        txt_nis.setText(String.valueOf(nis));
        txt_nama.setText(String.valueOf(nama));
        txt_tgl_lahir.setText(String.valueOf(tgl_lahir));
        txt_alamat.setText(String.valueOf(alamat));
        txt_mm.setText(String.valueOf(nilai_mm));
        txt_ipa.setText(String.valueOf(nilai_ipa));
        txt_bi.setText(String.valueOf(nilai_bi));
        txt_bing.setText(String.valueOf(nilai_bing));
      }catch(Exception e){}
    }//GEN-LAST:event_tabel_siswaMouseClicked

    private void btn_rata_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rata_kelasActionPerformed
      Object[] baris = {"Nilai Rata-Rata Kelas"};
      tabmode = new DefaultTableModel(null,baris);
      tabel_siswa.setModel(tabmode);
      try{
        hasil = crud.rata_kelas();
        while(hasil.next()){
          String[] data = {hasil.getString("rata_kelas")};
          tabmode.addRow(data);
        }
      } catch(Exception e){
      }
    }//GEN-LAST:event_btn_rata_kelasActionPerformed

    private void btn_rata_mapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rata_mapelActionPerformed
      Object[] baris = {"Rata-Rata MM", "Rata-Rata IPA", "Rata-Rata BI", "Rata-Rata BING"};
      tabmode = new DefaultTableModel(null,baris);
      tabel_siswa.setModel(tabmode);
      try{
        hasil = crud.rata_mapel();
        while(hasil.next()){
          String[] data = {hasil.getString("rata_mm"),hasil.getString("rata_ipa"),hasil.getString("rata_bi"),hasil.getString("rata_bing")};
          tabmode.addRow(data);
        }
      } catch(Exception e){
      }
    }//GEN-LAST:event_btn_rata_mapelActionPerformed

    private void btn_peringkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_peringkatActionPerformed
      Object[] baris = {"Peringkat","Nama", "Jumlah Nilai", "Nilai MM", "Nilai IPA", "Nilai BI", "Nilai BING"};
      tabmode = new DefaultTableModel(null,baris);
      tabel_siswa.setModel(tabmode);
      try{
        hasil = crud.peringkat_siswa();
        int i =1;
        while(hasil.next()){
          String[] data = {String.valueOf(i),hasil.getString("nama"),hasil.getString("jumlah_nilai"),hasil.getString("nilai_mm"),hasil.getString("nilai_ipa"),hasil.getString("nilai_bi"),hasil.getString("nilai_bing")};
          tabmode.addRow(data);
          i++;
        }
      } catch(SQLException e){
        System.out.println(e);
      }
    }//GEN-LAST:event_btn_peringkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
          for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
              if ("Nimbus".equals(info.getName())) {
                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                  break;
              }
          }
      } catch (ClassNotFoundException ex) {
          java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
          java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
          java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
          java.util.logging.Logger.getLogger(FormSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
          try {
            new FormSiswa().setVisible(true);
          } catch (SQLException ex) {
            Logger.getLogger(FormSiswa.class.getName()).log(Level.SEVERE, null, ex);
          }
        }
      });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_peringkat;
    private javax.swing.JButton btn_rata_kelas;
    private javax.swing.JButton btn_rata_mapel;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_semua;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_siswa;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_bi;
    private javax.swing.JTextField txt_bing;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_ipa;
    private javax.swing.JTextField txt_mm;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_tgl_lahir;
    // End of variables declaration//GEN-END:variables
}
